baseURL = "https://ericr.me/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Rosenberg Portfolio"
theme = "my-uilite"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Eric Rosenberg"
[params]
